services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/images:/app/images:ro
      - ./backend/thumbnails:/app/thumbnails:ro
      - ./backend/rounds:/app/rounds:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
